import:
  - ~/.dotfiles/config/alacritty/dracula-pro.yml
  #- ~/.dotfiles/config/alacritty/tokyonight.yml

# Window customization
window:
  dimensions:
    columns: 140
    lines: 38
  padding:
    x: 10
    y: 10
  decorations: buttonless
scrolling:
  history: 10000
  multiplier: 3
window.opacity: 0.75

# General Settings
live_config_reload: true

# Font configuration
font:
  normal:
    family: VictorMono Nerd Font Mono      
      #  style: Regular
      # bold:
      # family: JetBrainsMono Nerd Font
      # style: Bold
      # italic:
      # family: JetBrainsMono Nerd Font
      # style: Italic
  size: 12.0
  # offset:
  #  x: 0
  #  y: 0
  #glyph_offset:
  #  x: 0
  #  y: 0
  #debug:
  #  persistent_logging: false
  #draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

cursor:
  style: Beam
  unfocused_hollow: true

# Keybindings
key_bindings:
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: Insert, mods: Shift, action: PasteSelection }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: H, mods: Command|Control, action: Hide }
  - { key: M, mods: Command|Control, action: Minimize }
