# Window customization
window:
  dimensions:
    columns: 140
    lines: 38
  padding:
    x: 10
    y: 10
  decorations: none
scrolling:
  history: 10000
  multiplier: 3
background_opacity: 0.75

# General Settings
live_config_reload: true

# Font configuration
font:
  normal:
    family: Victor Mono
    style: Regular
  bold:
    family: Victor Mono
    style: Bold
  italic:
    family: Victor Mono
    style: Italic
  size: 11.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  debug:
    persistent_logging: false
draw_bold_text_with_bright_colors: true

# Terminal Color theme 'Nord'
colors:
  primary:
    background: '0x2E3440'
    foreground: '0xD8DEE9'
  cursor:
    text: '0x2E3440'
    cursor: '0xD8DEE9'
  normal:
    black: '0x3B4252'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x88C0D0'
    white: '0xE5E9F0'
  bright:
    black: '0x4C566A'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x8FBCBB'
    white: '0xECEFF4'

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

cursor:
  style: Beam
  unfocused_hollow: true

# Keybindings
key_bindings:
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: Insert, mods: Shift, action: PasteSelection }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: H, mods: Command|Control, action: Hide }
  - { key: M, mods: Command|Control, action: Minimize }
