#!/usr/bin/env zsh

# `shell_env.sh` is a main file for any general-case utils.
#
# This file is used as a source file for zsh.

# === Plugin management ===

antibody bundle < "$HOME/.antibody" > "$HOME/.zsh-plugins"
source "$HOME/.zsh-plugins"

# === Other shell parts ===

source "$HOME/.dotfiles/git/.aliases"
source "$HOME/.dotfiles/homebrew/.aliases"
source "$HOME/.dotfiles/zsh/.aliases"
# source "$HOME/.dotfiles/zsh/.development"

# === Development settings ===
typeset -U config_files
config_files=($DOTFILES/*/*.zsh)

# load everything but the path and completion files
for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}; do
  source "$file"
done

# === Local variables and overrides ===

if [[ -f "$HOME/.shell_env_local" ]]; then
  source "$HOME/.shell_env_local"
fi