- hosts: all
  roles:
    - common/gitconfig
    - common/fnm
    - osx/terminal
- hosts: all
  tasks:
    - name: install homebrew cask apps
      homebrew_cask:
        name:
          - postman
          - sublime-text
          - sublime-merge
          - docker
          - android-studio
        state: present

- hosts: all
  tasks:
    - name: install homebrew packages
      homebrew:
        name:
          - wifi-password
        state: present