#!/bin/zsh

#####################
# FLUTTER SETTINGS  #
#####################
export PATH="$PATH:$HOME/.development/flutter/bin"

#####################
# GO SETTINGS       #
#####################
export PATH="$PATH:/usr/local/go/bin"

###########################
# ANDROID STUDIO SETTINGS #
###########################
# export PATH="$PATH:/opt/android-studio/bin"

#####################
# RVM VARIABLE      #
#####################
# export PATH="$PATH:$HOME/.rvm/bin"
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

