[tools]
uv = "latest"
dotnet = "latest"
node = "lts"
rust = "stable"
"npm:prettier" = "3.8.4"
"npm:markdownlint-cli2" = "0.22.1"
gitleaks = "8.30.1"
pnpm = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
